# fly.toml file generated for tdfl on 2022-10-12T18:49:15+08:00
​
app = "tdfl"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
​
[build]
  builder = "heroku/buildpacks:20"
​
[deploy]
  release_command = "sh ./release.sh"
​
​
[env]
  PORT = "8080"
  USERNAME = "postgres"
  PASSWORD = "c09a29c018d99aa508b9f406f36aa4d3d0387b2d1a6198da"
  DATABASE = "tdfl-db"
  HOST = "tdfl-db.internal"
  DIALECT = "postgres"
​
[experimental]
  allowed_public_ports = []
  auto_rollback = true
​
[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
​
  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80
​
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
​
  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"